[package]
name = "parser"
version = "0.1.0"
authors = ["achille"]
edition = "2018"

[dependencies]
ast = { path = "../ast" }
lexer = { path = "../lexer" }
types = { path = "../types" }
lalrpop-util = "0.16.3"

[build-dependencies]
lalrpop = "0.16.3"